services:
  stocks-api:
    build: .
    volumes:
      - ".env:/app/.env"
      - "./tetrosite/settings.py:/app/tetrosite/settings.py"

    ports:
      - "8000:8000"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450